### ISSUE TITLE
Not compiling under Windows / VS 2012

### ISSUE THREAD

**Issue by aknoerig** [hiroyuki/ofxArtnet#10]
I tried building the example project under VS 2012 and unfortunately it completely fails. After updating all the project paths in the config file, the first error I'm getting is that it doesn't understand the `__attribute__((packed))` syntax. After simply removing that, the next compile error comes up, etc.

Do you have a suggestion how to run it with VS 2012? Do I maybe need to follow libartnet's compilation instructions to build a .lib or .dll first (using MINGW)?

Thanks!

**Comment by hiroyuki** [comment]
I don't think you should do something for compiling this.
Now there is no windows here because I am out for a while.
Could you wait some days for it.
When I get back to home, I will check this.
thanks

**Comment by aknoerig** [comment]
Great, thanks! It could also just be the VS project settings that need to get properly adjusted.
In the meantime, I did build the dll using MinGW, but I couldn't get that to load either.
So I'm looking forward to your trial. :)

**Comment by hiroyuki** [comment]
Hello @aknoerig 
I checked this issue and found some maintenance is required.
I pushed latest one. So everything must be fine!

Thanks,

**Comment by aknoerig** [comment]
Awesome, works like a charm! You just need to fix the reference to icon.rc in the vcxproj - either add the file or remove the reference.
Thanks!
