### ISSUE TITLE
using another universe 

### ISSUE THREAD

**Issue by dimitre** [hiroyuki/ofxArtnet#11]
I'm trying to use DMX out 1 or 2 (universes) but no success to date. only DMX 0 is working
is this the right command? thanks
```
    anNode.setup("192.168.0.12", 1);

```

**Comment by hiroyuki** [comment]
The parameter you put 1 is not for the universe.
Please use 
    void sendDmx( string targetIp, int targetSubnet, int targetUniverse, const unsigned char* data512, int size );
for sending data to specific subnet/universe.
thanks.

**Comment by dimitre** [comment]
Thank you @hiroyuki but I can't run this command here. Looking at the code I can only see this function here: 
```
int ofxArtnet::sendDmx( string targetIp, const unsigned char* data512, int size )
```
in https://github.com/hiroyuki/ofxArtnet/blob/master/src/ofxArtnet.cpp file

**Comment by hiroyuki** [comment]
hey, @dimitre.
The problem was in merging some feature.
I found dropped updated in between some commits and solved it.
Please check current master?
thanks.

**Comment by dimitre** [comment]
I've just checked, compiled and tested with moving heads. Everything running fine! Thank you very much @hiroyuki
