### ISSUE TITLE
possibility to run setup again in an ofxArtnet object

### ISSUE THREAD

**Issue by dimitre** [hiroyuki/ofxArtnet#14]
If I accidentaly disconnect some of the ethernets from the hub and re-plug it the data stops flowing to it. 
I'm trying to run setup again but the ip address is already used. 
Is there a way of "clear" or release the ip to re-run setup?
It would be a nice update
Thanks.

**Comment by yangyangcv** [comment]
according to my test, you can just re-plug and the data will flow again. that is because artnet is based on UDP not TCP, you don't need to setup again.

**Comment by dimitre** [comment]
Thanks for the great library, I'm using it a lot on OS X 10.11 and 10.12 with different Artnet Controllers (mostly Lumikit Pro X4)
