### ISSUE TITLE
possibility of sendArtnet receive other kinds of data, like unsigned char

### ISSUE THREAD

**Issue by dimitre** [hiroyuki/ofxArtnet#20]
Hello, first of all thanks for the great addon. 
I've just noticed the complete rewrite. it would be great to accept other than ofPixels data too
Thank you

**Comment by hiroyuki** [comment]
thanks your comment.
what else do you want?

**Comment by dimitre** [comment]
unsigned char would be great!

**Comment by hiroyuki** [comment]
I added that function pls check.
