### ISSUE TITLE
how to send data to multiple universes

### ISSUE THREAD

**Issue by dimitre** [hiroyuki/ofxArtnet#21]
Hello Hiroyuki, I've noticed the recent rewrite and was wondering which was the correct usage for sending data to different universes.
As the universe is set in setup and protected I suppose I have to use a vector of ofxArtnetSender objects to send to multiple universes. Or maybe it is just some functionality missing and about to be implemented.
Feel free to close this issue. Thank you

**Comment by MatthijsHoekstra** [comment]
Hi Dimitri, I am facing the same problem currently. Did you already solve it? Thanks!

**Comment by dimitre** [comment]
Not yet, im still using legacy branch here to be able to use multiple universes

**Comment by MatthijsHoekstra** [comment]
Interesting, when I try to compile the legacy version (as I need the multiple universes) it gives me the following compile errors..
![image](https://user-images.githubusercontent.com/22255583/50693257-c02d8d80-1036-11e9-9cba-a81bf7fa4613.png)

Any chance you know why it gives them?

**Comment by MatthijsHoekstra** [comment]
Hi @hiroyuki ,

Thanks for the reply, do you have a working example? I am struggling with initializing the vector. 

I expected that 
`std::vector<ofxArtnetSender> artnets;` 
would be sufficient, but it is not working..

Thanks in advance!

**Comment by hiroyuki** [comment]
It is because ofxArtnetSender don't have copy constructor.
I added it on ofxArtnetSender.
Please pull the latest.

Or you can also use shared_ptr instead of <ofxArtnetSender>.

```C++
std::vector<shared_ptr<ofxArtnetSender>> artnets;
artnets.emplace_back(make_shared<ofxArtnetSender>());
artnets.back()->setup("10.0.0.11",0);//universe 0
artnets.emplace_back(make_shared<ofxArtnetSender>());
artnets.back()->setup("10.0.0.11",1);//universe 1
```

**Comment by dimitre** [comment]
> Hello @dimitre @MatthijsHoekstra
> Sorry for late reply.
> 
> In case you want to send data to different universes, you have to have a vector of ofxArtnetSender.
> 
> ```
> 	artnets.emplace_back(make_shared<ofxArtnetSender>());
> 	artnets.back()->setup("10.0.0.11",0);//universe 0
> 	artnets.emplace_back(make_shared<ofxArtnetSender>());
> 	artnets.back()->setup("10.0.0.11",1);//universe 1
> ```

Hello @hiroyuki in fact I've noticed if I use the optional universe parameter this addon doesn't work.
Maybe it is setting artnet port instead of universe? 
Thank you

**Comment by hiroyuki** [comment]
Oh, yes. You are right. it is the port address.
if you want to send to different universes, you need that in [ofxArtnetMessage](https://github.com/hiroyuki/ofxArtnet/blob/master/src/artnet/ofxArtnetMessage.h#L26)

`	inline void setUniverse15(unsigned int universe) { _portAddress = _universe = universe; }
	inline void setUniverse(unsigned int net, unsigned int subnet, unsigned int universe)
`

**Comment by hiroyuki** [comment]
@dimitre @MatthijsHoekstra
I re-opened this.
Please close if it is OK.

**Comment by dimitre** [comment]
Thank you! I'll be closing this one. everything is working here!
