### ISSUE TITLE
Artnet Receive doesn't output the correct universe number

### ISSUE THREAD

**Issue by Hantoo** [hiroyuki/ofxArtnet#27]
Artnet Receive doesn't output the correct universe number.
I am trying to receive 4 universes, however when I go m.getUniverse(); - the universe number is always 0 even if I send from a different universe.

**Comment by hiroyuki** [comment]
thank you for letting me know this.
I fix this bug.

**Comment by bwll1989** [comment]
When I try to receive 4 universes or more at the same time ，in most time just one universe can be read.i don't konw it's a bug or not
