### ISSUE TITLE
Add Support for Broadcast

### ISSUE THREAD

**Issue by Tenkir** [hiroyuki/ofxArtnet#28]
Currently this library only seems to support unicast. It should support broadcast.

**Comment by hiroyuki** [comment]
you can send it by a broadcast address.
https://en.wikipedia.org/wiki/Broadcast_address

**Comment by stephanschulz** [comment]
I have tried 192.168.1.255 but my artnet devices do not respond. they only respond with direct IP address like 192.168.1.101, 192.168.1.102, etc

I am on macOS 13 with OF12

**Comment by stephanschulz** [comment]
changing the `udp.Connect` here https://github.com/hiroyuki/ofxArtnet/blob/f0915ca99a890a501605bd7c9fae1af7c0d551aa/src/artnet/ofxArtnetSender.cpp#L27
to `udp.ConnectMcast` seems to make broadcast work.
```
ofxArtnetSender::ofxArtnetSender(const ofxArtnetSender& origin)
{
	udp.Create();
	// udp.Connect(targetIp.c_str(), targetPort);
	std::string ipAddressCopy = targetIp;
    char* ipAddressPtr = &ipAddressCopy[0];
	udp.ConnectMcast(ipAddressPtr, targetPort);
}

void ofxArtnetSender::setup(const std::string& ipAddress, const uint16_t port)
{
	this->targetIp = ipAddress;
	this->targetPort = port;
	udp.Create();
    udp.SetEnableBroadcast(true);
	// udp.Connect(ipAddress.c_str(), port);

	// Create a non-const copy of the string
    std::string ipAddressCopy = ipAddress;
    char* ipAddressPtr = &ipAddressCopy[0];
	udp.ConnectMcast(ipAddressPtr, port);
}
```
